### ISSUE TITLE
subsecond precision

### ISSUE THREAD

**Issue by raylu** [Squalm/GoClock#4]
I noticed `timeRemaining{Left,Right}` track the number of seconds left. most game clocks use at least tenths of a second, which is especially important for Fischer time in blitz situations

**Comment by Squalm** [comment]
That makes a lot of sense. I had previously considered using tenths but avoided it because the way I'm timing it with `window.setinterval()` (which is possibly not the best way) is a little bit slow and will loose some time each iteration. I didn't want to exagerrate this effect if I could avoid it, so I might try implementing 10ths and then testing it to see how accurate it is, or if I can find another better way of timing it (suggestions appreaciated). Thanks!

**Comment by raylu** [comment]
store the time the clock started for the player. when your interval callback fires, check the time again and see how much time has passed. don't update the time the clock started until the player hits the clock (so you don't build up time spent in JS)

**Comment by Squalm** [comment]
Great idea thanks!
